name: Testing

on: [push, pull_request]

jobs:
  maria11_3:
    name: MariaDB 11.3
    uses: ./.github/workflows/tests-maria.yml
    with:
      version: "11.3"
  maria11_4:
    name: MariaDB 11.2
    uses: ./.github/workflows/tests-maria.yml
    with:
      version: "11.4"

  mysql8_3:
    name: MySQL 8.3
    uses: ./.github/workflows/tests-mysql.yml
    with:
      version: "8.3"

  mysql8_4:
    name: MySQL 8.4
    uses: ./.github/workflows/tests-mysql.yml
    with:
      version: "8.4"

  pgsql15:
    name: PostgreSQL 17
    uses: ./.github/workflows/tests-pgsql.yml
    with:
      version: 17
  pgsql16:
    name: PostgreSQL 18
    uses: ./.github/workflows/tests-pgsql.yml
    with:
      version: 18

  sqlite:
    name: SQLite
    uses: ./.github/workflows/tests-sqlite.yml

  sqlsrv2022_latest:
    name: Microsoft SQL Server 2022 (Latest)
    uses: ./.github/workflows/tests-sqlsrv.yml
    with:
      version: 2022-latest
